{% set name = "htbuilder" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/htbuilder-{{ version }}.tar.gz
  sha256: 9979a4fb6e50ce732bf6f6bc0441039dcaa3a3fc70689d8f38f601ed8a1aeec0

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<35]

requirements:
  host:
    - python 
    - pip
    - setuptools
    - wheel
  run:
    - python 
    - more-itertools

test:
  imports:
    - htbuilder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tvst/htbuilder
  dev_url: https://github.com/tvst/htbuilder
  doc_url: https://github.com/tvst/htbuilder/blob/master/README.md
  summary: A purely-functional HTML builder for Python. Think JSX rather than templates.
  description: |
    htbuilder lets you build HTML strings using a purely functional syntax in Python. Why use 
    templating languages when you can just use functions?
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - ELundby45
